#!/bin/bash

echo "Getting the latest versions of each submodule"
git submodule foreach --recursive git checkout master

for dir in $(find ./ -maxdepth 1 -type d); do
        if [ -e "$dir/sync" ]; then
            cd $dir
            echo "Syncing $dir"
            ./sync
            cd ..
        fi
done
